version: "3.8"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=sertifikasi
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  api:
    image: cihuyyama/sertifikasi-api:latest
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - db
    volumes:
      - api_uploads:/app/public/notulensi
 
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

volumes:
  db_data:
  api_uploads: