version: "3.8"
services:
  # db:
  #   image: mysql:8.0
  #   restart: always
  #   environment:
  #     - MYSQL_DATABASE=sertifikasi
  #     - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - db_data:/var/lib/mysql

  api:
    build:
      context: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - DOMAIN=${DOMAIN}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    # depends_on:
    #   - db
  
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --label-enable

# volumes:
  # db_data:
